plugin: amazon.awws.aws_ec2
regions:
  - us-east-1
filters: 
  ag:Environment:dev 
  instance-state-name:running 
compose: 
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Environment
    prefix: env
    