
- name: Collect Managed Nodes meraki_static_route
  hosts: env_dev
  become: true 
  gather_facts: true 
  tasks:
    - name: Install sysstat (for mpstat)
      apt:
        name: sysstat
        state: present
      when: ansible_os_family == "Debian"

    - name: install sysstat (RedHat/CentOS)
      yum:
        name: sysstat 
        state:  present
      when: ansible_os_family == "RedHat"

    - name: Get CPU usage via mpstat
      shell: "mpstat 11 | awk '/Average/&& $NF ~ /[0-9]+/{print 100 - $NF}'"
      register: cpu_usage 
    
    - name: Get memory usage
      shell: "free | awk '/Mem:/ {printf(\"%.2f\"), $3/$2 * 100}'"
      register: mem_usage

    - name: Get disk usage 
      shell: "df / | awk 'NR==2 {print $5}'"
      register: disk_usage

    - name: Set matrics facter
      set_fact: 
        metrics: 
          hostname  : "{{ inventory_hostname }}"
          cpu_usage : "{{cpu_usage.stdout | float | round(2)}}"
          mem_usage : "{{ mem_usage.stdout | float | round (2) }}"
          disk_usage: "{{ disk_usage.stdout | float | round (2) }}"