# [linux]
# ansible-control ansible_host=192.168.57.10 ansible_user=vagrant
# ubuntu_node1    ansible_host=192.168.57.11 ansible_user=vagrant
# centos-node1    ansible_host=192.168.57.13 ansible_user=vagrant
# suse-node1      ansible_host=192.168.57.12 ansible_user=vagrant
# jenkins-server  ansible_host=192.168.57.20 ansible_user=vagrant



[webservers]
ubuntu_node1    ansible_host=192.168.57.11
centos-node1    ansible_host=192.168.57.13
suse-node1      ansible_host=192.168.57.12
jenkins-server  ansible_host=192.168.57.20


; [ubuntu]
; 192.168.57.11
; 192.168.57.20
; 
; [suse]
; 192.168.57.12
; 
; [centos]
; 192.168.57.13
; 
; [linux:children]
; ubuntu
; suse
; centos

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
