---
- name: Master Web Server Playbook
  hosts: all
  become: true

  tasks:
    - name: Install Apache Package
      package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present

    - name: Ensure Apache Service is Running
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

    