- name: Managed OS Patching
  hosts: all
  become: true
  tasks:
    - name: Pre-Patching Cleanup (Free up /boot space)
      shell: |
        apt-get autoremove -y
        apt-get clean
      when: ansible_distribution == "Ubuntu"

    - name: Update Ubuntu (with extra patience)
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
        dpkg_options: 'force-confold,force-confdef' # Cleaned up the quotes/dashes
      register: apt_res
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: ansible_distribution == "Ubuntu" # Using 'distribution' is more precise for Ubuntu
      async: 1800 
      poll: 10

    - name: Update SUSE
      zypper:
        name: '*'
        state: latest
      when: ansible_os_family == "Suse"

      # Webhook automation confirmed!