---
- name: Configure Web Servers
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache Web Server for Debian 
      include_tasks: install_apache.yml
      when: ansible_os_family == "Debian"

    - name: Install Apache Web Server for Suse 
      include_tasks: install_apache_suse.yml
      when: ansible_os_family == "Suse"


